### PR TITLE
Add -insecure option to skip TLS certificate verification

### LINKED ISSUE #7: "tls: failed to verify certificate: x509: certificate signed by unknown authority" error when executing
Is there a way to skip certificate validation?

### PR DESCRIPTION
**Pull request by xnyo**
Adds `-insecure` flag to skip TLS verification when making HTTP requests to 

```
./detect-angular-dashboards -j -insecure https://localhost:3000/api
```

This can be used to use the program against instances that have a self-signed certificate.

Fixes #7

### CODE REVIEW

**Comment by toporek3112** [comment]
Any progress here?

**Review by briangann — APPROVED** [review]
works great, tested against local setup

```SHELL
./dist/darwin_amd64/detect-angular-dashboards -j https://localhost:3000/api
2024/04/17 09:30:57 Detecting Angular dashboards for "https://localhost:3000/api"
get frontend settings: do request: Get "https://localhost:3000/api/frontend/settings": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

vs

```SHELL
./dist/darwin_amd64/detect-angular-dashboards -j -insecure https://localhost:3000/api
2024/04/17 09:30:48 Detecting Angular dashboards for "https://localhost:3000/api"
null
```

**Comment by xnyo** [comment]
Hi @toporek3112 , this has been added in the latest release: https://github.com/grafana/detect-angular-dashboards/releases/tag/v0.8.0

**Comment by toporek3112** [comment]
Perfect, thank you guys!

**Pull request merged**
